#code base taken from: https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
# command to install dependencies
#install:
 # - pip install -r requirements.txt
 # - pip install .
# command to run tests
script: nosetests

